compiler:
  - clang
  - gcc
cache:
  apt: true
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages:
      #- lcov
      - rubygems
      - clang-3.8
      - g++-5
      - gcc-5
before_install: git submodule update --init
install:
  - export PLATFORM=$(uname -s)
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5" CCOV="gcov-5" USE_COVERAGE="lcov" USE_COVERALLS=1; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.8"; fi
  - |
    if [ "${USE_COVERALLS}" = '1' ]; then
      if [ "${USE_COVERAGE}" = 'gcov' ]; then easy_install cpp-coveralls; fi
      if [ "${USE_COVERAGE}" = 'lcov' ]; then 
        pwd
        git clone https://github.com/linux-test-project/lcov.git ./lcov
        cd lcov
        sudo make install
        cd ..
        pwd
        gem install lcoveralls; 
      fi
    fi
language: cpp
script:
  - make Release USE_COVERAGE=0 && ./test/test.out && ./sample/sample.out && make clean && make Debug && ./test/test.out && ./sample/sample.out
after_success:
  # Coverage
  - if [ "${USE_COVERALLS}" = '1' ]; then cd ./test; make send-coveralls; fi
