compiler:
  - clang
  - gcc
cache:
  apt: true
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
      - llvm-toolchain-precise
    packages:
      - clang-3.8
      - g++-5
      - gcc-5
before_install: git submodule update --init
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.8" CC="clang-3.7"; fi
language: cpp
script:
#  - chmod a+x ./test.sh
  - make Debug CXX="${CXX}" && make Release CXX="${CXX}" && ./test/bin/"${CXX}"/"${uname -s}"/Debug/test.out  && ./test/bin/"${CXX}"/"${uname -s}"/Release/test.out && ./sample/bin/"${CXX}"/"${uname -s}"/Debug/sample.out && ./sample/bin/"${CXX}"/"${uname -s}"/Release/sample.out
