compiler:
  - clang
  - gcc
sudo: required
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
      - llvm-toolchain-precise
    packages:
      #- lcov
      - ruby
      - clang-6.0
      - g++-7
      - gcc-7
before_install: git submodule update --init
install:
  - export PLATFORM=$(uname -s)
  - if [ "$CXX" = "g++" ]; then export CXX="g++-7" CC="gcc-7" CCOV="gcov-7" USE_COVERAGE="lcov" USE_COVERALLS=1; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-6.0" CC="clang-6.0"; fi
  - |
    if [ "${USE_COVERALLS}" = '1' ]; then
      if [ "${USE_COVERAGE}" = 'gcov' ]; then easy_install cpp-coveralls; fi
      if [ "${USE_COVERAGE}" = 'lcov' ]; then
        pwd
        git clone https://github.com/linux-test-project/lcov.git ./lcov
        cd lcov
        sudo make install
        cd ..
        pwd
        gem install specific_install
        gem specific_install -l 'git://github.com/pcolby/lcoveralls.git';
      fi
    fi
language: cpp
script:
  - make Release USE_COVERAGE=0 && ./test/test.out && ./sample/sample.out && make clean && make Debug && ./test/test.out && ./sample/sample.out
after_success:
  # Coverage
  - if [ "${USE_COVERALLS}" = '1' ]; then cd ./test; make send-coveralls; fi
